### ISSUE TITLE
Android APK being zipped

### ISSUE THREAD

**Issue by lunarcloud** [itchio/butler#199] opened 2019-10-07 02:25 UTC
This is bad as phone users often can't unzip things - expect to download APKs directly.

Using command:
`butler -v push export/android/name-of-game.apk "samsarette/name-of-game:android"`

This happened after upgrading butler recently

**Comment by fasterthanlime** [comment] 2019-10-07 09:52
Hey there, you're absolutely right.

This isn't due to a butler upgrade, but to a bug I unwittingly introduced in its backend (while fixing another). I'm taking a look now.

**Comment by fasterthanlime** [comment] 2019-10-07 10:40
A fix has been deployed.

**Closed by fasterthanlime** 2019-10-07 10:40 UTC

**Comment by ricardocostaza** [comment] 2022-03-31 23:19
> A fix has been deployed.

I think we have a regression. Push a APK file result in a ZIP.
